-- ============================================================
-- ai_models: AI 模型配置表
-- 用途：统一管理所有 AI 模型，支持前端动态加载模型列表
-- 管理员可在 Supabase Dashboard 直接增删改查，无需改前端代码
-- ============================================================

-- 1. 创建模型表
create table if not exists ai_models (
  id bigint generated by default as identity primary key,
  value text not null unique,        -- 模型标识，如 "google/gemini-3.1-flash-image-preview"
  label text not null,               -- 简短显示名，如 "Base" / "Gemini 3.1 Flash"
  description text not null default '', -- 描述/副标题，如 "Google" / "base model"
  provider text not null default '',  -- 提供商，如 "Google" / "OpenAI" / "xAI"
  category text not null default 'image-generation', -- 分类：image-generation, design, video
  is_active boolean not null default true,  -- 是否启用，false 则前端不展示
  sort_order integer not null default 0,    -- 排序权重，越小越靠前
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. 索引：按分类 + 启用状态 + 排序查询
create index if not exists idx_ai_models_category_active
  on ai_models (category, is_active, sort_order);

-- 3. 插入初始数据
insert into ai_models (value, label, description, provider, category, sort_order) values
  ('google/gemini-3.1-flash-image-preview', 'Base', 'base model', 'Google', 'image-generation', 1),
  ('openai/gpt-5.4-image-2', 'Pro', 'pro model', 'OpenAI', 'image-generation', 2),
  ('grok-4-1-fast-non-reasoning', 'Grok 4.1 Fast', 'design model', 'xAI', 'design', 1);

-- 4. 开启 RLS（行级安全）
alter table ai_models enable row level security;

-- 5. RLS 策略：公开可读（前端无需登录也可获取模型列表）
create policy "ai_models 公开可读"
  on ai_models for select
  using (true);

-- 仅 authenticated 角色可写（管理员通过 Dashboard 管理）
create policy "ai_models 仅认证用户可写"
  on ai_models for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- 6. 自动更新 updated_at 触发器
create or replace function update_ai_models_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_ai_models_updated_at
  before update on ai_models
  for each row
  execute function update_ai_models_updated_at();